apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aks-test-webapp-pdb
spec:
  minAvailable: 2 # Ensure at least 2 replicas are available during voluntary disruptions
  selector:
    matchLabels:
      app: aks-test-webapp