# ClusterIP service for the web application
apiVersion: v1
kind: Service
metadata:
  name: aks-test-webapp-service
  labels:
    app: aks-test-webapp
spec:
  selector:
    app: aks-test-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
# By default clusterIP ensure internal loadBalancing between pods with round-robin and decouples the need of POD IP/name to route traffic as they can change upon restart
  type: ClusterIP